import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  SafeAreaView,
} from 'react-native';
import Header from '../components/Header';
import FloatingNavbar from '../components/FloatingNavbar';

const PrivacyPolicyScreen = () => {
  // Get current date in format: June 15, 2023
  const formattedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  return (
    <SafeAreaView style={styles.container}>
      <Header title="Privacy Policy" showBackButton={true} />
      
      <ScrollView style={styles.content}>
        <View style={styles.section}>
          <Text style={styles.lastUpdated}>Last Updated: {formattedDate}</Text>
          
          <Text style={styles.sectionTitle}>1. Introduction</Text>
          <Text style={styles.paragraph}>
            Welcome to Captionator ("we," "our," or "us"). We are committed to protecting your privacy 
            and ensuring you have a positive experience when using our app. This Privacy Policy explains 
            how we collect, use, disclose, and safeguard your information when you use our mobile application.
          </Text>
          <Text style={styles.paragraph}>
            Please read this Privacy Policy carefully. By accessing or using our app, you acknowledge that 
            you have read, understood, and agree to be bound by all the terms outlined in this Privacy Policy.
          </Text>
          
          <Text style={styles.sectionTitle}>2. Information We Collect</Text>
          <Text style={styles.subSectionTitle}>2.1 Personal Information</Text>
          <Text style={styles.paragraph}>
            We may collect personal information that you voluntarily provide to us when you:
          </Text>
          <Text style={styles.bulletPoint}>• Register for an account</Text>
          <Text style={styles.bulletPoint}>• Use our caption generation features</Text>
          <Text style={styles.bulletPoint}>• Contact our customer support</Text>
          <Text style={styles.bulletPoint}>• Participate in promotions or surveys</Text>
          <Text style={styles.paragraph}>
            This information may include your name, email address, profile picture, and other details 
            necessary to provide our services.
          </Text>
          
          <Text style={styles.subSectionTitle}>2.2 Profile Images</Text>
          <Text style={styles.paragraph}>
            When you upload a profile picture, the image is stored in our Firestore database in base64 format. 
            This allows your profile picture to be consistently displayed across all your devices when you sign in 
            to your account. These images are stored securely and are only accessible to you through your account.
          </Text>
          <Text style={styles.paragraph}>
            You can update or remove your profile picture at any time through the app's profile settings.
            If you delete your account, all associated data including your profile picture will be permanently removed 
            from our systems.
          </Text>
          
          <Text style={styles.subSectionTitle}>2.3 Images for Caption Generation</Text>
          <Text style={styles.paragraph}>
            When you use our caption generation features, we process the images you upload to generate 
            captions. These images are processed securely and are not permanently stored on our servers 
            beyond the time needed to generate captions. We do not use these images for any purpose other 
            than providing the caption generation service to you.
          </Text>
          
          <Text style={styles.subSectionTitle}>2.4 Saved Captions</Text>
          <Text style={styles.paragraph}>
            When you save captions generated by our app, we store these captions in our Firestore database 
            associated with your account. This allows you to access your saved captions across devices. 
            The saved captions do not include the original images used to generate them.
          </Text>
          
          <Text style={styles.subSectionTitle}>2.5 Usage Information</Text>
          <Text style={styles.paragraph}>
            We automatically collect certain information about your device and how you interact with our app, 
            including:
          </Text>
          <Text style={styles.bulletPoint}>• Device information (model, operating system)</Text>
          <Text style={styles.bulletPoint}>• IP address and approximate location information</Text>
          <Text style={styles.bulletPoint}>• App usage statistics and preferences</Text>
          <Text style={styles.bulletPoint}>• Error logs and performance data</Text>
          
          <Text style={styles.sectionTitle}>3. How We Use Your Information</Text>
          <Text style={styles.paragraph}>
            We use the information we collect to:
          </Text>
          <Text style={styles.bulletPoint}>• Provide, maintain, and improve our services</Text>
          <Text style={styles.bulletPoint}>• Process and generate captions for your images</Text>
          <Text style={styles.bulletPoint}>• Store and display your profile picture across your devices</Text>
          <Text style={styles.bulletPoint}>• Save and retrieve your generated captions</Text>
          <Text style={styles.bulletPoint}>• Communicate with you about updates and features</Text>
          <Text style={styles.bulletPoint}>• Respond to your inquiries and support requests</Text>
          <Text style={styles.bulletPoint}>• Monitor and analyze usage patterns and trends</Text>
          <Text style={styles.bulletPoint}>• Detect, prevent, and address technical issues</Text>
          
          <Text style={styles.sectionTitle}>4. Data Storage and Security</Text>
          <Text style={styles.paragraph}>
            We use Google Firebase services, including Firebase Authentication and Firestore Database, 
            to store and manage user data. Your profile images are stored in Firestore in base64 format, 
            and your account information is managed through Firebase Authentication.
          </Text>
          <Text style={styles.paragraph}>
            We implement appropriate technical and organizational measures to protect your personal 
            information against unauthorized access, alteration, disclosure, or destruction. However, 
            no method of transmission over the Internet or electronic storage is 100% secure, and we 
            cannot guarantee absolute security.
          </Text>
          
          <Text style={styles.sectionTitle}>5. Third-Party Services</Text>
          <Text style={styles.paragraph}>
            Our app integrates with the following third-party services:
          </Text>
          <Text style={styles.bulletPoint}>• Google Firebase for authentication and data storage</Text>
          <Text style={styles.bulletPoint}>• OpenAI API for caption generation</Text>
          <Text style={styles.bulletPoint}>• Expo services for app functionality</Text>
          <Text style={styles.paragraph}>
            These third parties may collect information about you when you use our app. We encourage you 
            to review the privacy policies of these third parties:
          </Text>
          <Text style={styles.bulletPoint}>• Google Firebase: https://firebase.google.com/support/privacy</Text>
          <Text style={styles.bulletPoint}>• OpenAI: https://openai.com/policies/privacy-policy</Text>
          <Text style={styles.bulletPoint}>• Expo: https://expo.dev/privacy</Text>
          
          <Text style={styles.sectionTitle}>6. Your Rights</Text>
          <Text style={styles.paragraph}>
            Depending on your location, you may have certain rights regarding your personal information, 
            including:
          </Text>
          <Text style={styles.bulletPoint}>• Access to your personal information</Text>
          <Text style={styles.bulletPoint}>• Correction of inaccurate information</Text>
          <Text style={styles.bulletPoint}>• Deletion of your personal information</Text>
          <Text style={styles.bulletPoint}>• Objection to certain processing activities</Text>
          <Text style={styles.paragraph}>
            To exercise these rights, please contact us using the information provided in the "Contact Us" 
            section. You can also delete your account and associated data directly through the app settings.
          </Text>
          
          <Text style={styles.sectionTitle}>7. Data Retention</Text>
          <Text style={styles.paragraph}>
            We retain your personal information for as long as necessary to provide you with our services 
            and as needed to comply with our legal obligations. If you delete your account, we will delete 
            or anonymize your personal information, including your profile picture and saved captions, 
            within 30 days, unless we are required to retain it for legal purposes.
          </Text>
          
          <Text style={styles.sectionTitle}>8. Children's Privacy</Text>
          <Text style={styles.paragraph}>
            Our app is not intended for children under the age of 13. We do not knowingly collect personal 
            information from children under 13. If you are a parent or guardian and believe your child has 
            provided us with personal information, please contact us immediately so we can take appropriate 
            steps to remove such information.
          </Text>
          
          <Text style={styles.sectionTitle}>9. International Data Transfers</Text>
          <Text style={styles.paragraph}>
            Your information may be transferred to, and maintained on, computers located outside of your 
            state, province, country, or other governmental jurisdiction where the data protection laws 
            may differ from those in your jurisdiction. If you are located outside the United States and 
            choose to provide information to us, please note that we transfer the data to the United States 
            and process it there.
          </Text>
          
          <Text style={styles.sectionTitle}>10. Changes to This Privacy Policy</Text>
          <Text style={styles.paragraph}>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting 
            the new Privacy Policy on this page and updating the "Last Updated" date. You are advised to 
            review this Privacy Policy periodically for any changes. Significant changes will be notified 
            to you either through the email address you have provided or by placing a prominent notice in our app.
          </Text>
          
          <Text style={styles.sectionTitle}>11. Contact Us</Text>
          <Text style={styles.paragraph}>
            If you have any questions or concerns about this Privacy Policy or our data practices, please 
            contact us at:
          </Text>
          <Text style={styles.contactInfo}>Email: chhabrapranav2001@gmail.com</Text>
          <Text style={styles.contactInfo}>Website: https://pranavchhabra.com</Text>
        </View>
      </ScrollView>
      
      <FloatingNavbar />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  section: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 20,
    marginBottom: 80, // Extra padding for the floating navbar
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 2,
  },
  lastUpdated: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 20,
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1f2937',
    marginTop: 24,
    marginBottom: 12,
  },
  subSectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
    marginTop: 16,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 16,
    color: '#4b5563',
    lineHeight: 24,
    marginBottom: 16,
  },
  bulletPoint: {
    fontSize: 16,
    color: '#4b5563',
    lineHeight: 24,
    marginLeft: 16,
    marginBottom: 8,
  },
  contactInfo: {
    fontSize: 16,
    color: '#4338ca',
    marginLeft: 16,
    marginBottom: 8,
  },
});

export default PrivacyPolicyScreen; 